language: ruby
cache: bundler
rvm: 2.3.1
before_install: gem install bundler -v 1.12.3
bundler_args: "--binstubs=./bundler_stubs"
before_script:
script:
  - bundle exec rake --trace before_commit:run_without_checks
  - git config --global user.email test@example.com
  - git config --global user.name "Test Example"
  - BUNDLE_GEMFILE=.overcommit_gems.rb bundle exec overcommit --run
  - bundle exec rspec
# Have this option to stop travis-ci building twice. Currently we have travis set to build both
# PR's and pushes. However this means when we push to a PR we have to wait for Travis to finish
# 2 builds. If we unticked 'pushes' when the PR was finally merged that would not be built. The
# brute force approach would be to untick build PR's and just build all pushes. We instead have
# gone with the approach outlined here http://stackoverflow.com/a/31882307
branches:
  only:
    - master

# This section was added as per https://docs.travis-ci.com/user/code-climate/
# To protect our codeclimate stats rather than adding the Codeclimate API key for ea-area_lookup
# in the open we used this guide https://docs.travis-ci.com/user/encryption-keys/ to encryt the
# value. Essentially install travis gem, then run `travis encrypt <my_code_climate_api_key>`
addons:
  code_climate:
    repo_token:
      secure: "DsWI1kzx5RIfB/QQysErQTW94FF6v512q3vqFChSXaAViJA6LgU9coBRiLtZ3RyE0YcvPzu0B1q/fqR4sDq4xG1L6VMY2PlF4ZI57AaPa1WFmzT9mCAhYCbpYKXuMySCoS4YvoHrHgwd30M0RYmiRtZY75Olmbd1PsbbZGfnIGwcEchujHb6oQ6WKgEAqq6zvHHf5QM18oSm4ZCFSYijGU7BvxMsLTToFuPnndGomWHCfMDSyBkC2wt5pmfdsjbirrsPPnFbYxCOCxGk77WWw9G+swUZclgUiUn1q2tSFgri27zufbFuGknDWf9HMiMqzgfCO8kut/78CqRjt5BtUm2otJLEhlpmL4t9rqDUKl/hmc+asxfoj04qP1cNRmjZf0QYbT4rFlsFlcNgYNcZcLf66ry9c8WXcpV6qvKukaT9Xyj1/KAVXDqO1EUd1oEBIoKnILW7H4Zhbjhu6lq2ga47Wux0IrMdtHE2RwjdtCxwfhkuUcblfnPpjW8tXeDND0nE/Se45rXZ/YwojZSeqyZCvZbcXMOvggzRQeAgi02sruw33oZU6W/f8VOjC5VrB1KEHm4j0n21dI6ENu0D+tbjBIW0TvI47hAuV/R1v7kHJVbSIcAedtxWt87mSdyQkOukCVSYHMOKJHY6T1EtZlK5V9RHDrHD8KIMeJV/Dx0="
deploy:
  provider: rubygems
  api_key:
    secure: BQYV2mKJ4LItAiYgYSW1ixVMIlk1ahzvbMXJz/xtH2XfZzT7T6r17VbjpH2pbJo5QbChwsWaZOAZq2nrPIsgrh09/liflZC010Qc60zIYqgB4LXOu7KM6XEpfSvc/NCf0NwPExIjF2jskuhAwQXJVWLCcDGEyUEGnNhn5NDPq7TXR9U0sQyY1MZfJvlQwUNgaOThGA7b6DzUiim7LpGTAs7PcBHKfgwr1hRqVQ0VMF1jZsdvVID9IPVqfojOrNnAzoN2MpgybhsUTkSueV6WaWPhbY0eXH2U0EKx9grlyb0TBHfYVSADC8tNKB/ooJv6ofHfL+cZTki4+gCKOmv+vs2IkNqs1fucLMwDaE48sI/9omvyPPD4t1SMAhA+IBCUGQdXz8CvIsLf6gf/N8srQnUv8QiAoHw1ArkCt4Y2D1iYAf8r+XGP4nuewVJwNHG+9qQILDz4xlCPUJFtBdbiDo1RjazoLtOhTfnSemXeDVl+GUE09fzO3iclBAN2wiGGLRy57SEs+VkQLmPGb9aaJ+LXuMgtr1lzqX0x4JdyG690qCoZcRF+uwDcnBX+HjJcZOzcHORpOlqJM8LaFl86oo3DrdnvJgpkumn3LllsS2CYOO191b3nWnN0lbEuLpT0TbtO4Mhk/YwDG9VZpbwAATiLBMd0IiAmlGbdZMw9ias=
  gem: ea-area_lookup
  on:
    tags: true
    repo: EnvironmentAgency/ea-area_lookup
    all_branches: true
